# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2.1
orbs:
  aws-cli: circleci/aws-cli@1.2.0
  cypress: cypress-io/cypress@1.25.0
jobs:
  build-dev:
    executor: cypress/default
    working_directory: ~/repo

    steps:
      - checkout
      - run: yarn
      - run: yarn lint
      - run: yarn test
      - run: yarn build

  deploy-dev:
    executor: aws-cli/default
    working_directory: ~/repo
    steps:
      - checkout
      - aws-cli/setup:
          aws-access-key-id: ${AWS_ACCESS_KEY_ID}
          aws-secret-access-key: ${AWS_SECRET_ACCESS_KEY}
          aws-region: ${AWS_REGION}
      - run:
          name: Downlaod Serverless State
          command: aws s3 sync s3://${CLIENT_SERVERLESS_STATE_BUCKET}/.serverless .serverless --delete

      - run: yarn
      - run: yarn global add serverless

      - run: env > .env
      - run: yarn deploy

      # ctest

workflows:
  version: 2
  build-and-deploy-dev:
    jobs:
      - build-dev:
          context: deadbear-io-dev
          filters:
            branches:
              only: development
      - deploy-dev:
          context: deadbear-io-dev
          requires:
            - build-dev
          filters:
            branches:
              only: development
