export const AUTH_SIGN_IN = 'AUTH_SIGN_IN'
export const AUTH_COMPLETE_NEW_PASSWORD = 'AUTH_COMPLETE_NEW_PASSWORD'
export const AUTH_SIGN_UP = 'AUTH_SIGN_UP'
export const AUTH_SIGN_UP_CONFIRM = 'AUTH_SIGN_UP_CONFIRM'
export const AUTH_CREATE_ACCOUNT = 'AUTH_CREATE_ACCOUNT'
export const AUTH_USER_DELETE = 'AUTH_USER_DELETE'

export const AUTH_CURRENT_SESSION = 'AUTH_CURRENT_SESSION'
export const AUTH_CURRENT_SESSION_RESET = 'AUTH_CURRENT_SESSION_RESET'

export const AUTH_CURRENT_USER = 'AUTH_CURRENT_USER'
export const AUTH_CURRENT_USER_RESET = 'AUTH_CURRENT_USER_RESET'
export const AUTH_UPDATE_ATTRS = 'AUTH_UPDATE_ATTRS'

export const AUTH_LOGOUT = 'AUTH_LOGOUT'
export const AUTH_FORGOT_PASSWORD = 'AUTH_FORGOT_PASSWORD'
export const AUTH_FORGOT_PASSWORD_RESET = 'AUTH_FORGOT_PASSWORD_RESET'
export const AUTH_FORGOT_PASSWORD_CONFIRM = 'AUTH_FORGOT_PASSWORD_CONFIRM'
export const AUTH_FORGOT_PASSWORD_CONFIRM_RESET = 'AUTH_FORGOT_PASSWORD_CONFIRM'
export const AUTH_CHANGE_PASSWORD = 'AUTH_CHANGE_PASSWORD'

export const USER_FIND = 'USER_FIND'
export const USER_FINDBYID = 'USER_FINDBYID'
export const USER_CURRENT_FINDBYID = 'USER_CURRENT_FINDBYID'
export const USER_CREATE = 'USER_CREATE'
export const USER_UPDATE = 'USER_UPDATE'
export const USER_DELETE = 'USER_DELETE'
export const USER_ACTIVATE = 'USER_ACTIVATE'

export const SALESFORCE_FIND = 'SALESFORCE_FIND'
export const SALESFORCE_FINDBYID = 'SALESFORCE_FINDBYID'
export const SALESFORCE_CREATE = 'SALESFORCE_CREATE'
export const SALESFORCE_UPDATE = 'SALESFORCE_UPDATE'
export const SALESFORCE_DELETE = 'SALESFORCE_DELETE'
export const SALESFORCE_ACTIVATE = 'SALESFORCE_ACTIVATE'

export const PLATFORM_DATA_CONTRACT_CHECK_FIND =
  'PLATFORM_DATA_CONTRACT_CHECK_FIND'
